name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright Tests
      run: npm run test

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      run: allure generate ./allure-results --clean -o ./allure-report

    - name: Package Allure Report for Download
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
